const errorHandler = require('../utils/errorHandler')
const db = require('../posgres')
const importData = require('../otherFunctions/importTable')


module.exports.get = async function (req, res) {
    try {
        const data = await db.query("SELECT * FROM data ORDER BY id")
        res.status(200).json(data.rows)
    } catch (e) {
        errorHandler(res, e)
    }
}

module.exports.getData = async function (req, res) {
    try {
        const data = await db.query(`SELECT * FROM ${req.query.data} ORDER BY id`)
        res.status(200).json({ data: data.rows, fields: data.fields })
    } catch (e) {
        errorHandler(res, e)
    }
}

module.exports.getTable = async function (req, res) {
    try {
        const table = await db.query(`SELECT COLUMN_NAME, DATA_TYPE 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE table_name = '${req.query.table}'`)
        res.status(200).json(table.rows)
    } catch (e) {
        errorHandler(res, e)
    }
}

module.exports.create = async function (req, res) {
    try {
        const { type } = req.body

        const newData = await db.query('INSERT INTO data (title) VALUES ($1) RETURNING *',
            [type], (err, result) => {
                if (err) {
                    errorHandler(result, err)
                } else {
                    db.query(`CREATE TABLE IF NOT EXISTS ${type}
                    (
                        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
                        CONSTRAINT ${type}_pkey PRIMARY KEY (id)
                    )`,
                        (err, result2) => {
                            if (err) {
                                console.log(err)
                                errorHandler(result2, err)
                            }
                            return res.status(200).json("Успех!")
                        })
                }
            })
    } catch (e) {
        errorHandler(res, e)
    }
}

module.exports.addUpdateField = async function (req, res) {
    try {
        const { changes, action } = req.body
        if (action) {
            //Создаём новую строку в таблице
            const newRow = await db.query(`INSERT INTO ${changes[3].table} ("${changes[2].column}") VALUES ($1) RETURNING *`,
                [changes[0].changes], (err, result) => {
                    if (err) {
                        console.log(err)
                        errorHandler(result, err)
                    } else {
                        return res.status(200).json(result.rows)
                    }
                })
        } else {
            //Редактируем имеющуюся строку в таблице
            const currentRow = await db.query(`UPDATE ${changes[3].table} SET "${changes[2].column}" = 
            $1 where id = ${changes[1].id} RETURNING *`, [changes[0].changes], (err, result) => {
                if (err) {
                    console.log(err)
                    errorHandler(result, err)
                } else {
                    return res.status(200).json(result.rows)
                }
            })
        }

    } catch (e) {
        console.log(e)
        errorHandler(res, e)
    }
}

module.exports.createField = async function (req, res) {
    try {
        const { name, type, title, countChar } = req.body
        if (countChar == null) {
            const newData = await db.query(`ALTER TABLE ${title}
            ADD ${name} ${type} NULL`, (err, result) => {
                if (err) {
                    console.log('err1', err)
                    errorHandler(result, err)
                } else {
                    return res.status(200).json("Успех!")
                }
            })
        } else {
            const newData = await db.query(`ALTER TABLE ${title}
            ADD ${name} ${type}(${countChar}) NULL`, (err, result) => {
                if (err) {
                    console.log('err2', err)
                    errorHandler(result, err)
                } else {
                    return res.status(200).json("Успех!")
                }
            })
        }

    } catch (e) {
        errorHandler(res, e)
    }
}

module.exports.addImportingData = async function (req, res) {
    try {
        const { tableName, columns, data } = req.body
        //Создание таблицы в бд
        importData.importTable(tableName, columns, data)
        const addData = db.query('INSERT INTO data (title) VALUES ($1) RETURNING *',
            [tableName], (err, result) => {
                if (err) {
                    errorHandler(result, err)
                } else { }
            })
        return res.status(200).json("Успех!")
    } catch (e) {
        errorHandler(res, e)
    }
}
