const errorHandler = require('../utils/errorHandler')
const db = require('../posgres')

module.exports.importTable = async function (tableName, columns, data) {
    //Создание таблицы в бд
    const newData = await db.query(`CREATE TABLE IF NOT EXISTS ${tableName} ()`,
        (err, result) => {
            if (err) {
                errorHandler(result, err)
            } else {
                //Создание колонок в таблице
                columns.forEach((column) => {
                    let type;
                    if (column == 'id') {
                        type = `integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START ${data.length + 1} MINVALUE 1 MAXVALUE 2147483647 CACHE 1 )`
                    } else {
                        type = 'text NULL'
                    }
                    const newColumn = db.query(`ALTER TABLE ${tableName}
                        ADD "${column}" ${type}`, (err, result) => {
                        if (err) {
                            console.log('err1', err)
                            errorHandler(result, err)
                        }
                    })
                })
                //Заполнение таблицы
                setTimeout(() => {
                    data.forEach((item, index) => {
                        let changeValues = []
                        //Подготовка элементов для передачи
                        item.forEach(element => {
                            changeValues.push(`'${element}'`)
                        });
                        if (changeValues.length != 0) {
                            let resultColumns = columns.map((item, index) => {
                                return '"' + item + '"';
                            })
                            changeValues = rec(resultColumns, changeValues)
                            const newRow = db.query(`INSERT INTO ${tableName} (${resultColumns.join(', ')}) VALUES ('${index + 1}', ${changeValues.join(', ')}) RETURNING *`,
                                (err, result) => {
                                    if (err) {
                                        console.log(err)
                                        errorHandler(result, err)
                                    }
                                })
                        }
                    })
                }, 1000)
            }
        })
}

function rec(data1, data2) {
    if (data1.length - 1 > data2.length) {
        data2.push("null")
        return rec(data1, data2)
    } else {
        return data2
    }
}